name: Deploy to VPS via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH connection to VPS
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOST }}
        username: root
        host: mc.hoaks.my.id
    - name: Deploy to VPS
      run: ssh root@mc.hoaks.my.id "cd /var/www/html && ls -la"
