name: Deploy to VPS via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        known-hosts: mc.hoaks.my.id

    - name: Deploy code to VPS
      run: |
          ssh root@mc.hoaks.my.id "cd /var/www/html/administrasi_koprasi && ls -la"
